In [1]:
from collections import abc
issubclass(tuple, abc.Sequence)

True

In [2]:
issubclass(list, abc.Sequence)

True

In [3]:
symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

In [7]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

[162, 163, 165, 8364, 164]

In [8]:
# using map and filter is not faster than the previous equivalent example
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

In [9]:
colors = ['white','black']
sizes = ['S','M','L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('white', 'S'),
 ('white', 'M'),
 ('white', 'L'),
 ('black', 'S'),
 ('black', 'M'),
 ('black', 'L')]

In [12]:
for color in colors:
    for size in sizes:
        print((color,size))

('white', 'S')
('white', 'M')
('white', 'L')
('black', 'S')
('black', 'M')
('black', 'L')


In [13]:
tshirts = [(color,size) for size in sizes
                        for color in colors]
tshirts

[('white', 'S'),
 ('black', 'S'),
 ('white', 'M'),
 ('black', 'M'),
 ('white', 'L'),
 ('black', 'L')]

In [14]:
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [16]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [18]:
# generators expressions is never built in memory (saves the cost of building a list)
colors = ['black','white']
sizes = ['S','M','L']
for tshirt in (f'{c} {s}' for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [29]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [23]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [31]:
# tuple is immutable but items that point to mutable items may change the tuple
a = (10, 'alpha', [1,2])
b = (10, 'alpha', [1,2])
a == b

True

In [32]:
b[-1].append(99)
a == b

False

In [33]:
b

(10, 'alpha', [1, 2, 99])

In [36]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True

tf = (10, 'alpha', (1,2))
tm = (10, 'alpha', [1,2])
fixed(tf)

True

In [37]:
fixed(tm)

False

In [40]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
latitude

33.9425

In [41]:
longitude

-118.408056

In [53]:
divmod(20,8)

(2, 4)

In [56]:
t = (20,8)
divmod(*t)

(2, 4)

In [57]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [58]:
import os
_, filename = os.path.split('/home/mathias/research2024/magicvirus.exe')
filename

'magicvirus.exe'

In [60]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [61]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [63]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [65]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [66]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [77]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

fun(*[1,2], 3, *range(4,7))

(1, 2, 3, 4, (5, 6))

In [81]:
*range(4), 4

(0, 1, 2, 3, 4)

In [82]:
[*range(4), 4]

[0, 1, 2, 3, 4]

In [83]:
{*range(4), 4, *(5,6,7)}

{0, 1, 2, 3, 4, 5, 6, 7}

In [84]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333,-99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611,-74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778,-46.635833))
]

In [97]:
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for name, _, _, (lat, lon) in metro_areas:
        if lon <= 0:
            print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

if __name__ == '__main__':
    main()

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


In [42]:
# using a match/case along with unpacking can read a lot better than if/else/elif and case/switch
# requires python >= 3.10, we describe "what" we want to match instead of "how" to match it.
def evaluate(exp, env) -> any:
    match exp:
        case ['quote', x]:
            return x
        case ['if', test, consequence, alternative]:
            if evalulate(test, env):
                return evaluate(consequence, env)
            else:
                return evaluate(alternative, env)
        case ['lambda', [*params], *body] if body:
            return Procedure(params, body, env)
        case ['define', Symbol() as name, value_exp]: # using Symbol() as name here avoids extra conditional
            evn[name] = evaluate(value_exp, env)
        case _:
            raise SyntaxError(listpstr(exp))

In [43]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [44]:
l[2:]

[30, 40, 50, 60]

In [45]:
s = 'roadrage'
s[::3]

'rdg'

In [46]:
s[::-1]

'egardaor'

In [48]:
s[::-2]


'eado'

In [70]:
# suppose this is a flat file db
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                 $17.50      3  $52.50
1489  6mm Tactile Switch x20            $4.95       2  $9.90
1510  Panavise Jr. - PV-201             $28.00      1  $28.00
1601  PiTFT Mini Kit 320x240            $34.95      1  $34.95
"""

In [71]:
SKU = slice(0,6)
DESCRIPTION = slice(6,40)
UNIT_PRICE = slice(40,52)
QUANTITY = slice(52,55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

$17.50       Pimoroni PiBrella                 
$4.95        6mm Tactile Switch x20            
$28.00       Panavise Jr. - PV-201             
$34.95       PiTFT Mini Kit 320x240            
 


In [83]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
l[2:5] = [20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [85]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [86]:
l[3::2] = [11,22]
l

[0, 1, 20, 11, 5, 22, 9]

In [87]:
l[2:5] = 100

TypeError: can only assign an iterable

In [88]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [89]:
l = [1,2,3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [90]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [92]:
# tictactoe
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [93]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [94]:
# this is not the perferred way as it references the same list making it useless
unplayable_board = [['_'] * 3] * 3
unplayable_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [95]:
unplayable_board[1][2] = 'O'
unplayable_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [96]:
# __imul__, and __iadd__ is in place add/multiply +=, *=
# since tuples are immutable it creates a new one in memory (str is the only exception)
l = [1,2,3]
id(l)

4443677568

In [97]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [98]:
id(l)

4443677568

In [99]:
t = (1,2,3)
id(t)

4444012480

In [100]:
t *= 2
id(t)

4444160064

In [101]:
# this raises an error and adds the values
t = (1,2,[30,40])
t[2] += [50,60]
t

TypeError: 'tuple' object does not support item assignment

In [102]:
t

(1, 2, [30, 40, 50, 60])

In [103]:
fruits = ['apple', 'raspberry', 'banana', 'grape']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [104]:
fruits

['apple', 'raspberry', 'banana', 'grape']

In [105]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [106]:
sorted(fruits, key=len)

['apple', 'grape', 'banana', 'raspberry']

In [107]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'apple', 'grape']

In [108]:
fruits

['apple', 'raspberry', 'banana', 'grape']

In [109]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [110]:
# array saves a lot of memory when you need to handle millions of floating-point values
# A deque (double-ended queue) is a more efficient FIFO data structure
# An array of float values does not hold full-fledged float instances but only packed bytes representing their machine values
from array import array
from random import random
floats = array('d', (random() for i in range(10**7))) # generator expression (because wrapped in ())
floats[-1]

0.44597693735830735

In [111]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [116]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.44597693735830735

In [117]:
floats2 == floats

True

In [118]:
# memoryview is a shared-memory sequence type that lets us handle slices of arrays
# without copying bytes (important for large data sets)
octets = array('B', range(6))
m1 = memoryview(octets)
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [119]:
m2 = m1.cast('B', [2,3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [120]:
m3 = m1.cast('B', [3,2])
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [121]:
m2[1,1] = 22
m3[1,1] = 33
octets

array('B', [0, 1, 2, 33, 22, 5])

In [125]:
numbers = array('h', [-2,-1,0,1,2])
memv = memoryview(numbers)
len(memv)

5

In [126]:
memv[0]

-2

In [127]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [128]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [1]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape

(12,)

In [4]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a[2]

array([ 8,  9, 10, 11])

In [6]:
a[2,1]

9

In [7]:
a[:,1]

array([1, 5, 9])

In [8]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
# thread safe, double-ended queue designed for fast inserting and removing from both ends
# NOTE: not optimized from removing items from the middle of list.
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [10]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [11]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [13]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [14]:
dq.extend([11,22,33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [15]:
dq.extendleft([10,20,30,40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)